### PR TITLE
Fix pending review status.

### LINKED ISSUE #757: Submitted object status should say "pending review"
Object dh053mt2395 has been submitted for review, but the status listed in the table on the dashboard and on the deposits table for the collection say "Draft - not deposited"

Item view page showing that it's pending review:
Image

Collection deposits table showing that it's in draft:
Image

Dashboard table for the collection showing that it's in draft:
Image

### PR DESCRIPTION
**Pull request by justinlittman**
closes #757

### CODE REVIEW

File: app/components/collections/show/deposits_component.rb [hunk 1]
```diff
@@ -32,12 +32,16 @@ def values_for(work)
...
+                                      version_status: work_statuses.fetch(work.druid, VersionStatus::NilStatus.new),
+                                      work_form: WorkForm.new)
+
+        presenter.status_message
       end
 
       def persistent_link_for(work)
         if work.druid.nil?
-          'N/A (still depositing)'
+          ''
```
Comment (justinlittman) [inline app/components/collections/show/deposits_component.rb:44]: This is consistent with other parts of the app.

File: app/components/collections/show/deposits_component.rb [hunk 2]
```diff
@@ -13,9 +13,9 @@ def initialize(presenter:)
       delegate :collection, :work_statuses, to: :presenter
 
       def collection_deposits
-        @collection_deposits ||= collection.works.map do |work|
+        @collection_deposits ||= collection.works.order(:title).map do |work|
```
Comment (justinlittman) [inline app/components/collections/show/deposits_component.rb:16]: Makes testing easier.
