### PR TITLE
Scope works on collection works page. Fix collection permissions for …

### LINKED ISSUE #1124: Clicking on deposit in collection view of deposit list takes user to H3 homepage
I was on a zoom with Kathy Kerns (kkerns), and in the deposit list for the collection "Welcome to your review-required fake capstone collection", she clicked on the first deposit - "2024 Consolidated AI Inventory", and landed on the H3 Homepage. We were able to replicate this a few times.

Image

### PR DESCRIPTION
**Pull request by justinlittman**
…collection owner.

closes #1124

### CODE REVIEW

File: app/controllers/collections_controller.rb [hunk 1]
```diff
@@ -82,7 +82,9 @@ def wait
   def works
     authorize! @collection
 
-    @works = @collection.works.order(:title).page(params[:page])
+    @works = authorized_scope(@collection.works, as: :collection, type: :relation,
```
Comment (justinlittman) [inline app/controllers/collections_controller.rb:85]: This is where the scope is set for the collection works.

File: app/policies/collection_policy.rb [hunk 2]
```diff
@@ -9,7 +9,7 @@ def show?
   end
 
   def manage?
-    collection_manager? || record.user_id == user.id
+    collection_manager?
```
Comment (justinlittman) [inline app/policies/collection_policy.rb:12]: The collection owner shouldn't be a manager.

File: app/policies/collection_policy.rb [hunk 3]
```diff
@@ -24,10 +24,7 @@ def review?
     collection_reviewer? || collection_manager?
   end
 
-  # TODO: Add a rule for collection managers & depositors
```
Comment (justinlittman) [inline app/policies/collection_policy.rb:27]: cruft

File: app/controllers/collections_controller.rb (hunk 1 above)
Comment (mjgiarlo) [reply app/controllers/collections_controller.rb:85]: @justinlittman Did you find you needed to pass the `type: :relation` kwargs? For some reason I thought that was the default value but I could be mistaken.

File: app/policies/work_policy.rb [hunk 4]
```diff
@@ -21,6 +21,14 @@ def review?
     collection_reviewer? || collection_manager?
   end
 
+  scope_for :relation, :collection do |relation, collection:|
```
Comment (mjgiarlo) [inline app/policies/work_policy.rb:24]: Since we're likely to be primarily using AR scopes, this could be shortened to:

```suggestion
  relation_scope(:collection) do |relation, collection:|
```

https://actionpolicy.evilmartians.io/#/scoping?id=active-record-scopes

**Review by mjgiarlo — APPROVED** [review]
Approve pending consideration of minor feedback

File: app/controllers/collections_controller.rb (hunk 1 above)
Comment (justinlittman) [reply app/controllers/collections_controller.rb:85]: If I made both of your suggested changes, this worked. Thanks!
