### PR TITLE
Handle work types that have multiple genres.

### LINKED ISSUE #398: Cocina::Models::ValidationError related to work type
DepositWorkJob will fail if "Data" is selected as a work type and the work is saved as draft. 

Error from job:

```
Message	#/components/schemas/DescriptiveStructuredValue expected object, but received Array: [{"type"=>"genre", "value"=>"Data sets", "uri"=>"http://id.loc.gov/authorities/genreForms/gf2018026119", "source"=>{"code"=>"lcgft"}}, {"type"=>"genre", "value"=>"dataset", "source"=>{"code"=>"local"}}]
```

### PR DESCRIPTION
**Pull request by justinlittman**
closes #398

### CODE REVIEW

File: app/services/to_cocina/work/types_mapper.rb [hunk 1]
```diff
@@ -68,7 +68,7 @@ def genres
         return [] if work_type == 'Other'
 
         # Uniq avoids adding dupe genres when same genre in from type and subtype.
```
Comment (lwrubel) [inline app/services/to_cocina/work/types_mapper.rb:70]: Not part of your code change, but typo?
```suggestion
        # Uniq avoids adding dupe genres when same genre is from type and subtype.
```

**Review by lwrubel — APPROVED** [review]
