### PR TITLE
Fix mapping to cocina collection for licenses.

### LINKED ISSUE #801: Collection roundtrip failed
## Backtrace

    line 24 of [PROJECT_ROOT]/app/services/to_collection_form/roundtrip_validator.rb: ToCollectionForm::RoundtripValidator#call
    line 7 of [PROJECT_ROOT]/app/services/to_collection_form/roundtrip_validator.rb: ToCollectionForm::RoundtripValidator.roundtrippable?
    line 104 of [PROJECT_ROOT]/app/controllers/collections_controller.rb: CollectionsController#editable?

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/128495/faults/117314369)

### PR DESCRIPTION
**Pull request by justinlittman**
closes #801

### CODE REVIEW

File: app/services/to_cocina/collection/mapper.rb [hunk 1]
```diff
@@ -48,7 +48,12 @@ def request_params
       end
 
       def access
-        { view: 'world', license: collection_form.license }.compact_blank!
+        { view: 'world' }.tap do |params|
+          if collection_form.license_option == 'required' && collection_form.license.present?
+            params[:license] =
+              collection_form.license
```
Comment (mjgiarlo) [inline app/services/to_cocina/collection/mapper.rb:54]: Stray newline?

**Review by mjgiarlo — APPROVED** [review]
Approve pending feedback

File: app/services/to_cocina/collection/mapper.rb (hunk 1 above)
Comment (justinlittman) [reply app/services/to_cocina/collection/mapper.rb:54]: Thanks rubo. Fixed.
