### PR TITLE
Fix validation of whats changing.

### LINKED ISSUE #1048: User should not be able to deposit without comments in "What's changing" box
See https://app.honeybadger.io/projects/128495/faults/118281532.

- I opened an already-deposited item for editing.
- Clicked over to the deposit tab
- The "what's changing" box was there but I did not fill it in
- I clicked the deposit button and the validation did not catch the empty box and triggered the above alert.

### PR DESCRIPTION
**Pull request by justinlittman**
closes #1048

### CODE REVIEW

File: app/forms/work_form.rb [hunk 1]
```diff
@@ -96,7 +96,7 @@ def persisted?
   validates :create_date_type, inclusion: { in: %w[single range] }
 
   attribute :whats_changing, :string
-  validates :whats_changing, presence: true, if: -> { persisted? && version > 1 }
+  validates :whats_changing, presence: true
```
Comment (justinlittman) [inline app/forms/work_form.rb:99]: The problem is that this didn't validate when the user was making a change to a deposited version 1 (since at that time the version was still 1 it bypassed the validation).

Unfortunately, this state can't be detected without having access to version status, so took a different approach to the validation by providing a dummy value when an open first version.

File: spec/forms/work_form_spec.rb [hunk 2]
```diff
@@ -248,81 +262,4 @@
       expect(form.custom_rights_statement).to eq("This is a test.\r\n\r\nThis is a second paragraph.")
     end
   end
-
-  describe 'Whats changing validation' do
```
Comment (justinlittman) [inline spec/forms/work_form_spec.rb:252]: Good news is I could get rid of all of these tests.

**Review by mjgiarlo — APPROVED** [review]
